#!/usr/bin/env bash
. "$(dirname "$0")/_/husky.sh"

LC_ALL=C

local_branch="$(git rev-parse --abbrev-ref HEAD)"

valid_branch_regex="^(feature|hotfix|epic|bugfix|release)\/[a-z0-9._-]+$"

message="Ooops... There is something wrong with your branch name. Branch names in this project must adhere to this contract: $valid_branch_regex. Your commit will be rejected. You should rename your branch to a valid name and try again."

if [[ $local_branch != "develop" ]] && [[ $local_branch != "main" ]] && [[ $local_branch != *"release/"* ]];
then
  if [[ ! $local_branch =~ $valid_branch_regex ]];
  then
    echo "$message"
    exit 1
  fi
fi

yarn lint --fix .

exit 0
